### PR TITLE
Styles merge last

### PR DESCRIPTION
**Pull request by B-Tanonaka**

### CODE REVIEW

**Review by yaleyang5 — APPROVED** [review]
Looks great Brett!

**Comment by B-Tanonaka** [comment]
Home-Event Carousel3

**Comment by B-Tanonaka** [comment]
Home-CreateEventOrPost

**Comment by B-Tanonaka** [comment]
Community-Search

**Comment by B-Tanonaka** [comment]
Comment-Lift:Drop

**Comment by B-Tanonaka** [comment]
Comment-Individual

**Comment by B-Tanonaka** [comment]
Profile-Communities

**Comment by B-Tanonaka** [comment]
Profile-Friends

**Comment by B-Tanonaka** [comment]
Profile-Stats

**Comment by B-Tanonaka** [comment]
Home-Dark Mode

**Comment by B-Tanonaka** [comment]
Login

**Comment by B-Tanonaka** [comment]
Messages-From Profile Friends

**Comment by B-Tanonaka** [comment]
Profile-Stats

**Comment by B-Tanonaka** [comment]
Home-Dark

**Comment by B-Tanonaka** [comment]
Messages-List

**Comment by B-Tanonaka** [comment]
Home-Bottom Navigation

**Comment by B-Tanonaka** [comment]
Profile-Clicking Stats

**Comment by B-Tanonaka** [comment]
Profile-Add Stat

**Comment by B-Tanonaka** [comment]
Profile-Communities

**Comment by B-Tanonaka** [comment]
Profile-Friends

**Comment by B-Tanonaka** [comment]
Profile-Stats

**Comment by B-Tanonaka** [comment]
Login

**Comment by B-Tanonaka** [comment]
Login-Signup

**Comment by B-Tanonaka** [comment]
Login-Forgot Password

**Comment by B-Tanonaka** [comment]
Login

**Pull request merged**
